### ISSUE TITLE
[django 1.9a1] add_to_builtins removed

### ISSUE THREAD

**Issue by Kondou-ger** [nigma/django-easy-pjax#11]
In django 1.9a1 `add_to_builtins` [was removed](https://docs.djangoproject.com/en/dev/releases/1.9/#django-template-base-add-to-builtins-is-removed). You're now supposed to put this into `settings.TEMPLATES['OPTIONS']['builtins']`.

@nigma If there is any hope of it getting merged and released I may make a PR that introduces a code side check whether we're in django 1.9+ and add documentation on putting easy-pjax into template options.

------

Traceback:
```python-traceback
(project)kondou:project/ (master) $ ./manage.py shell
Traceback (most recent call last):
  File "/home/kondou/git/project/lib/python3.4/site-packages/easy_pjax/__init__.py", line 15, in <module>
    from django.template import add_to_builtins
ImportError: cannot import name 'add_to_builtins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/kondou/git/project/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/kondou/git/project/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/kondou/git/project/lib/python3.4/site-packages/easy_pjax/__init__.py", line 18, in <module>
    from django.template.base import add_to_builtins
ImportError: cannot import name 'add_to_builtins'

**Comment by kmmbvnr** [comment]
I have to integrate django-easy-pjax directly into my project.

If someone interested here is the code that perform autoregister on django 1.8 and 1.9

https://github.com/viewflow/django-material/blob/master/material/frontend/__init__.py#L11

**Comment by wrichert** [comment]
Any chance that this PR will be pulled into main repository?

**Comment by avelis** [comment]
@wrichert I do am onboard with a pull-request. Lack of Django 1.9 support is creating a hinderance from using this library.

Sadly I am not sure if it will get added.

**Comment by nigma** [comment]
Hey, a new version addressing this issue is on PyPI (https://pypi.python.org/pypi/django-easy-pjax/). Thanks everyone for using this package.
